```{r setumaps, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(vroom)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Maps

This chapter only help creating maps for field sampling.
Results can be found in the `maps` folder wen run locally;

```{r speciesmaps}
species <- data.frame(Genus = c("Symphonia", "Dicorynia", "Tachigali"), Selected = 1, DBHmature = c(17, 22, 15)) # from @Hardy2005
```

```{r datamaps}
crs_rot = "+proj=omerc +lat_0=36.934 +lonc=-90.849 +alpha=0 +k_0=.7 +datum=WGS84 +units=m +no_defs +gamma=20"
data <- vroom("data/inventories/paracou.tsv") %>%
  filter(Plot == "16") %>% 
  left_join(species) %>%
  mutate(DBH = CircCorr/pi) %>% 
  st_as_sf(coords = c("Xutm", "Yutm"),
           crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0') %>% 
  filter(Selected == 1) %>% 
  mutate(label = paste0(TreeFieldNum, "_", substr(Genus, 1, 1))) %>% 
  st_transform(data, crs = crs_rot)
limits <- st_read("data/shapefiles/OverallPlots/OverallPlots.shp", quiet = T) %>% 
  filter(Plot == 16, Subplot %in% unique(data$SubPlot)) %>% 
  st_transform(crs = crs_rot)
contour <- st_read("data/shapefiles/ContourLinesPlots/ContourLinePlots.shp", quiet = T) %>% 
  st_transform(contour, crs = crs_rot)
```

```{r mapfun}
map_subplot <- function(subplot) {
  sublimits <- filter(limits, Subplot == subplot)
  subcontour <- st_crop(contour, sublimits)
  subdata <- st_crop(data, sublimits)
  g <- ggplot() +
    geom_sf(data = subcontour, fill = NA, col = "lightgrey") +
    geom_sf(data = sublimits, fill = NA, col = "darkgrey", text = subplot) +
    geom_sf_text(subdata = limits, label = subplot, colour = "darkgrey") +
    geom_sf(data = subdata, aes(shape = Genus), col = "black", size = 3) +
    ggrepel::geom_text_repel(
      data = subdata,
      aes(label = label, geometry = geometry),
      stat = "sf_coordinates",
      min.segment.length = 0
    ) +
    theme(axis.title = element_blank(), axis.text = element_blank(), 
          axis.ticks = element_blank(), axis.line = element_blank()) +
    scale_color_discrete(guide = "none") +
    ggtitle(paste("SubPlot:", subplot))
  ggsave(g, file = paste0("subplot", subplot, ".pdf"), path = 'maps', 
         width = 297, height = 420, unit = 'mm', dpi = 300, bg = "white")
}
```


```{r map, eval=F}
lapply(c(8:10, 13:15, 18:20), map_subplot)
```
