```{r setuppreli, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(vroom)
library(sf)
library(terra)
library(patchwork)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Preliminary analyses

```{r}
seedlings <- st_read("save/trilateration/Data_saplings_est.shp", quiet = T)
twi <- rast("data/rasters/TWI_1m.tif")
twi <- crop(twi, seedlings)
dcm <- rast("data/rasters/DCM2016_FTH22.tif")
dcm <- crop(dcm, seedlings)
seedlings$twi <- extract(twi, vect(seedlings))$TWI_1m
seedlings$dcm <- extract(dcm, vect(seedlings))$DCM2016_FTH22
```

```{r}
g1 <- ggplot(seedlings) +
  geom_raster(data = as.data.frame(twi, xy = T), aes(x = x, y = y, fill = TWI_1m)) +
  geom_sf(aes(col = specie)) +
  scale_color_manual("Species", values = c("blue", "red", "green")) +
  ggtitle("TWI") +
  theme_minimal()
g2 <- ggplot(seedlings) +
  geom_raster(data = as.data.frame(dcm, xy = T), aes(x = x, y = y, fill = DCM2016_FTH22)) +
  geom_sf(aes(col = specie)) +
  scale_color_manual("Species", values = c("blue", "red", "green")) +
  ggtitle("DCM") +
  theme_minimal()
g1 + g2
```


```{r}
g1 <- ggplot(seedlings, aes(twi, fill = specie)) + geom_density(alpha = 0.5, col = NA) + scale_x_log10() +
  scale_fill_manual("Species", values = c("green", "red", "blue")) +
  ggtitle("TWI")
g2 <- ggplot(seedlings, aes(dcm, fill = specie)) + geom_density(alpha = 0.5, col = NA) +
  scale_fill_manual("Species", values = c("green", "red", "blue")) +
  ggtitle("DCM")
g1 / g2
```

```{r}
seedlings %>% 
  st_drop_geometry() %>% 
  mutate(XY = paste0(X,Y)) %>% 
  group_by(specie, XY, Carre) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(as.factor(Carre), log(N), fill = as.factor(Carre))) +
  geom_boxplot() +
  facet_wrap(~specie) +
  ggpubr::stat_compare_means()
```

```{r}
paracou <- read_tsv("data/inventories/paracou.tsv") %>% 
  filter(Plot == "16") %>% 
  filter(CensusYear == 2020) %>% 
  filter(Genus %in% c("Symphonia", "Tachigali", "Dicorynia")) %>% 
  filter(CircCorr/pi > 15) %>% 
  st_as_sf(coords = c("Xutm", "Yutm"),
           crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
get_distance_genus <- function(genus){
  sub_seedlings <- filter(seedlings, specie == str_sub(genus, 1, 1))
  sub_adult <- filter(paracou, Genus == genus)
  distance <- st_distance(sub_seedlings, sub_adult) %>% 
    as_data_frame() %>% 
    mutate(ind = 1:n()) %>% 
    gather(neighbour, distance, -ind) %>% 
    group_by(ind) %>% 
    summarise(distance = min(distance))
  sub_seedlings$distance_neighbour <- distance$distance
  return(sub_seedlings)
}
 lapply(c("Symphonia", "Tachigali", "Dicorynia"), 
                    get_distance_genus) %>% 
  bind_rows() %>% 
  ggplot(aes(as.numeric(distance_neighbour), fill = specie)) +
  geom_density(alpha = 0.5, col = NA) +
  scale_x_sqrt() +
  ggtitle("Distance to closest adult")
```


```{r}
readxl::read_xlsx("data/inventories/Plantules répertoriées finale.xlsx") %>% 
  ggplot(aes(Hauteur, as.numeric(Nb_folioles), col = str_sub(Id, 1, 1))) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  scale_y_log10()
```

